# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path:  /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/validation_data_joint_200.npy
  label_path: /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/validation_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 1380
  num_point: 21
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.assembly101_hands.AdjMatrixGraph


# test
phase: test
device: [0]
test_batch_size: 16
weights: /home/salman/msg3d_exp/handpose/work_dir/weights/weights-43-8676.pt # Example weights from epoch 43

work_dir: /home/salman/msg3d_exp/handpose/work_dir/
save_score: True
