work_dir: /home/salman/msg3d_exp/handpose/work_dir

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/train_data_joint_200.npy
  label_path: /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/validation_data_joint_200.npy
  label_path: /home/salman/msg3d_exp/handpose/HAND_GCN/share_contex25_thresh0/validation_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 1380 # NUMBER OF FINE-GRAINED ACTIONS
  num_point: 21
  num_person: 2 # Two hands as two separate entities
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.assembly101_hands.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 50
device: [0]
batch_size: 16
forward_batch_size: 8
test_batch_size: 8
nesterov: True

